apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mydomainname.com
  dnsName:
    - santitham.me
    - www.santitham.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - santitham.me
          - www.santitham.me